// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"study-gozero-demo/mall/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/order/OrderAdd",
				Handler: orderAddHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/order/get",
				Handler: getOrderHandler(serverCtx),
			},
		},
	)
}
