// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Id     int `json:"id"`
	UserId int `json:"userid"`
}

type OrderReply struct {
	Id          int    `json:"id"`
	Productname string `json:"productname"`
}

type OrderAddReq struct {
	Productname string `json:"productname"`
	Price       string `json:"price"`
	Unit        string `json:"unit"`
}

type OrderAddRes struct {
	Code     int    `json:"code"`
	Messsage string `json:"message"`
}
